deterministic:
  - _target_: monai.transforms.LoadImaged
    keys: [image]
  - _target_: monai.transforms.EnsureChannelFirstd
    keys: [image]
  - _target_: monai.transforms.ClampIntensityd
    keys: [image]
    min: 0.0
    max: 10.0
  - _target_: monai.transforms.EnsureTyped
    keys: [image, Label]
random:
  - _target_: monai.transforms.RandScaleIntensityd
    keys: [image]
    factors: 0.10
    prob: 0.5
  - _target_: monai.transforms.RandShiftIntensityd
    keys: [image]
    offsets: 0.10
    prob: 0.5
  - _target_: monai.transforms.RandRotated
    keys: [image]
    range_x: 0.08726646259971647   # np.deg2rad(5)
    range_y: 0.08726646259971647
    range_z: 0.08726646259971647
    mode: bilinear
    align_corners: false
    prob: 0.5
  - _target_: monai.transforms.RandFlipd
    keys: [image]
    spatial_axis: 1
    prob: 0.5
  - _target_: monai.transforms.RandFlipd
    keys: [image]
    spatial_axis: 2
    prob: 0.5
  - _target_: monai.transforms.ToTensord
    keys: [image, Label]
val:
  - _target_: monai.transforms.LoadImaged
    keys: [image]
  - _target_: monai.transforms.EnsureChannelFirstd
    keys: [image]
  - _target_: monai.transforms.ClampIntensityd
    keys: [image]
    min: 0.0
    max: 10.0
  - _target_: monai.transforms.EnsureTyped
    keys: [image, Label]
  - _target_: monai.transforms.ToTensord
    keys: [image, Label]